name: Deploy
on:
  push:
    branches:
      - main
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy 🚀
    steps:
      
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploying
        id: deployment
        uses: juancarlosjr97/divio-deploy-action@v1
        env:
          DIVIO_LOGIN_ACCESS_TOKEN: ${{ secrets.DIVIO_LOGIN_ACCESS_TOKEN }}
          DIVIO_REMOTE_PROJECT_ID: ${{ secrets.DIVIO_REMOTE_PROJECT_ID }}
      - if: steps.deployment.outputs.DEPLOYMENT_STATUS == 'success'
        name: Get DEPLOYMENT_STATUS
        run: echo "RESULT ${{ steps.hello.outputs.DEPLOYMENT_STATUS }}"
